user mosquitto
max_queued_messages 200
message_size_limit 0
allow_duplicate_messages false
connection_messages true
log_timestamp true

autosave_interval 8000
autosave_on_changes true

per_listener_settings true

listener 1883
allow_anonymous true
